apiVersion: v1
kind: Service
metadata:
  labels:
    app: sensor-app
    datasource: raspi-desk    
  name: raspi-temp-app
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: sensor-app
    datasource: raspi-desk    
status:
  loadBalancer: {}
