apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    datasource: raspi-desk
  name: grafana
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 3000
  type: LoadBalancer
  selector:
    app: grafana
    datasource: raspi-desk
