apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
    datasource: raspi-desk
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      datasource: raspi-desk
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        datasource: raspi-desk
    spec:
      containers:
        - image: grafana/grafana:7.3.6
          name: grafana
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
