apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: prometheus-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
