apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
    scrape_configs:
    - job_name: 'app'
      static_configs:
      - targets: [raspi-temp-app:5000]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-configmap
