apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    datasource: raspi-desk
  name: raspi-temp-prometheus
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  type: LoadBalancer
  selector:
    app: prometheus
    datasource: raspi-desk

