apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
    datasource: raspi-desk
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      datasource: raspi-desk
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
        datasource: raspi-desk
    spec:
      containers:
        - args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention.time=30d
            - --web.console.libraries=/usr/share/prometheus/console_libraries
            - --web.console.templates=/usr/share/prometheus/consoles
          image: prom/prometheus:v2.23.0
          name: prometheus
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /etc/prometheus/
              name: prometheus-config
            - mountPath: /prometheus
              name: prometheus-data
      restartPolicy: Always
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-configmap
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data-pvc
      nodeSelector:
        raspi-disk: large
status: {}
